# Generated by Django 3.0.3 on 2020-02-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='approval_date',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='proposal',
            name='completion_date',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='proposal',
            name='creation_date',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposal_status',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
