# Generated by Django 3.0.3 on 2020-02-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_blog', '0002_auto_20200228_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='approval_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='completion_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_status',
            field=models.IntegerField(default=0),
        ),
    ]
