# Generated by Django 3.0.3 on 2020-02-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_blog', '0004_auto_20200228_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
