# Generated by Django 3.0.3 on 2020-03-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_blog', '0005_auto_20200228_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='attachment',
        ),
    ]
