# Generated by Django 3.0.3 on 2020-03-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino_blog', '0007_auto_20200305_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='references',
            field=models.TextField(default='None'),
        ),
    ]
